apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-proto-d
  labels:
    app: hello-proto
spec:
  selector:
    matchLabels:
      app: hello-proto
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-proto
    spec:
      containers:
      - name: hello-proto
        image: bdelmas/hello-proto:0.0.1
        imagePullPolicy: Never
        ports:
        - name: hello-proto-s
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: hello-proto-s
spec:
  selector:
    app: hello-proto
  ports:
  - port: 50051
    targetPort: hello-proto-s
