apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-proto-deployment
  labels:
    app: hello-proto
spec:
  selector:
    matchLabels:
      app: hello-proto
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-proto
    spec:
      containers:
      - name: hello-proto
        image: bdelmas/hello-proto
        ports:
        - name: hello-proto-service
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: hello-proto-service
spec:
  selector:
    app: hello-proto
  ports:
  - port: 3000
    targetPort: hello-proto-service
